workflows:
  ios-workflow:
    name: iOS Workflow (Simulator & Release)
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      vars:
        XCODE_WORKSPACE: "Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
      xcode: 15.4
      cocoapods: default
      flutter: stable  # 3.35.1 以上をサポート
    scripts:
      - name: Set up Flutter environment
        script: |
          flutter config --enable-ios
          flutter --version
          flutter pub get
      - name: Install CocoaPods dependencies
        script: |
          cd ios
          pod install --repo-update
          pod update Flutter
      - name: Build for iOS Simulator (Debug)
        script: |
          FLUTTER_BUILD_IOS_SKIP_CODESIGN=true flutter build ios \
            --simulator \
            --no-codesign \
            --debug
      - name: Build iOS Release
        script: |
          FLUTTER_BUILD_IOS_SKIP_CODESIGN=true flutter build ios \
            --release \
            --no-codesign
    artifacts:
      - /tmp/xcodebuild_logs/*.log
      - build/ios/iphonesimulator/*.app
      - build/ios/ipa/*.ipa
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM