workflows:
  ios-workflow:
    name: iOS Workflow (Simulator & Release)
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      vars:
        XCODE_WORKSPACE: "Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
      xcode: 15.4
      cocoapods: default
      flutter: stable  # または特定のバージョン例: 3.22.0 (Dart 3.9.0を含む最新を確認)
    scripts:
      - name: Set up Flutter environment
        script: |
          flutter config --enable-ios
          flutter pub get
      - name: Install CocoaPods dependencies
        script: |
          cd ios
          pod install
      - name: Build for iOS Simulator (Debug)
        script: |
          FLUTTER_BUILD_IOS_SKIP_CODESIGN=true flutter build ios \
            --simulator \
            --no-codesign \
            --debug \
            --destination 'platform=iOS Simulator,name=iPhone 15 Pro,OS=18.0'
      - name: Build iOS Release
        script: |
          FLUTTER_BUILD_IOS_SKIP_CODESIGN=true flutter build ios \
            --release \
            --no-codesign
      - name: Additional Xcode build (optional)
        script: |
          xcodebuild build \
            -workspace "$XCODE_WORKSPACE" \
            -scheme "$XCODE_SCHEME" \
            -sdk iphonesimulator \
            -destination 'platform=iOS Simulator,name=iPhone 15 Pro,OS=18.0' \
            -configuration Debug \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO
    artifacts:
      - /tmp/xcodebuild_logs/*.log
      - build/ios/iphonesimulator/*.app
      - build/ios/ipa/*.ipa
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM