workflows:
  ios-workflow:
    name: iOS Workflow (Simulator & Release)
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      vars:
        XCODE_WORKSPACE: "Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
      xcode: 15.4
      cocoapods: default
      flutter: stable  # 3.35.1 以上をサポート
    scripts:
      - name: Set up Flutter environment
        script: |
          flutter config --enable-ios
          flutter --version
          flutter clean  # プロジェクトをクリーンに
          flutter pub get
      - name: Install CocoaPods dependencies
        script: |
          cd ios
          pod deintegrate  # CocoaPods をリセット
          pod cache clean --all  # キャッシュをクリア
          pod install --repo-update  # 依存関係を再インストール
          pod update Flutter  # Flutter ポッドを更新
      - name: Build for iOS Simulator (Debug)
        script: |
          FLUTTER_BUILD_IOS_SKIP_CODESIGN=true flutter build ios \
            --simulator \
            --no-codesign \
            --debug
      - name: Build iOS Release
        script: |
          FLUTTER_BUILD_IOS_SKIP_CODESIGN=true flutter build ios \
            --release \
            --no-codesign
          # 未署名の .app から .ipa を手動作成
          mkdir -p build/ios/ipa
          cd build/ios/Release-iphoneos
          zip -r Runner.ipa Runner.app
          mv Runner.ipa ../../ipa/
    artifacts:
      - /tmp/xcodebuild_logs/*.log
      - build/ios/iphonesimulator/*.app
      - build/ios/ipa/*.ipa
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM